"""
Canonical :func:`NodeSpec.type_id` strings for engine topology and hard-rules.

**AUTO-GENERATED** — run ``python backend/scripts/gen_artifacts.py``.
The canonical set is :data:`engine.registry.NODE_SPECS` keys; import from here
instead of string literals. Do not edit by hand.
"""
from __future__ import annotations

ALERT_TRIGGER = "ALERT_TRIGGER"
COMMS_COLLECTOR = "COMMS_COLLECTOR"
CONSOLIDATED_SUMMARY = "CONSOLIDATED_SUMMARY"
DATA_HIGHLIGHTER = "DATA_HIGHLIGHTER"
DECISION_RULE = "DECISION_RULE"
EXECUTION_DATA_COLLECTOR = "EXECUTION_DATA_COLLECTOR"
FEATURE_ENGINE = "FEATURE_ENGINE"
MARKET_DATA_COLLECTOR = "MARKET_DATA_COLLECTOR"
ORACLE_DATA_COLLECTOR = "ORACLE_DATA_COLLECTOR"
REPORT_OUTPUT = "REPORT_OUTPUT"
SECTION_SUMMARY = "SECTION_SUMMARY"
SIGNAL_CALCULATOR = "SIGNAL_CALCULATOR"

__all__ = [
    "ALERT_TRIGGER",
    "COMMS_COLLECTOR",
    "CONSOLIDATED_SUMMARY",
    "DATA_HIGHLIGHTER",
    "DECISION_RULE",
    "EXECUTION_DATA_COLLECTOR",
    "FEATURE_ENGINE",
    "MARKET_DATA_COLLECTOR",
    "ORACLE_DATA_COLLECTOR",
    "REPORT_OUTPUT",
    "SECTION_SUMMARY",
    "SIGNAL_CALCULATOR",
]
