"""
Canonical :func:`NodeSpec.type_id` strings for engine topology and hard-rules.

**AUTO-GENERATED** — run ``python backend/scripts/gen_artifacts.py``.
The canonical set is :data:`engine.registry.NODE_SPECS` keys; import from here
instead of string literals. Do not edit by hand.
"""
from __future__ import annotations

ALERT_TRIGGER = "ALERT_TRIGGER"
COMMS_COLLECTOR = "COMMS_COLLECTOR"
CONSOLIDATED_SUMMARY = "CONSOLIDATED_SUMMARY"
DATA_HIGHLIGHTER = "DATA_HIGHLIGHTER"
DECISION_RULE = "DECISION_RULE"
EXECUTION_DATA_COLLECTOR = "EXECUTION_DATA_COLLECTOR"
EXTRACT_LIST = "EXTRACT_LIST"
EXTRACT_SCALAR = "EXTRACT_SCALAR"
FEATURE_ENGINE = "FEATURE_ENGINE"
GROUP_BY = "GROUP_BY"
MAP = "MAP"
MARKET_DATA_COLLECTOR = "MARKET_DATA_COLLECTOR"
ORACLE_DATA_COLLECTOR = "ORACLE_DATA_COLLECTOR"
REPORT_OUTPUT = "REPORT_OUTPUT"
SECTION_SUMMARY = "SECTION_SUMMARY"
SIGNAL_CALCULATOR = "SIGNAL_CALCULATOR"
TIME_WINDOW = "TIME_WINDOW"

__all__ = [
    "ALERT_TRIGGER",
    "COMMS_COLLECTOR",
    "CONSOLIDATED_SUMMARY",
    "DATA_HIGHLIGHTER",
    "DECISION_RULE",
    "EXECUTION_DATA_COLLECTOR",
    "EXTRACT_LIST",
    "EXTRACT_SCALAR",
    "FEATURE_ENGINE",
    "GROUP_BY",
    "MAP",
    "MARKET_DATA_COLLECTOR",
    "ORACLE_DATA_COLLECTOR",
    "REPORT_OUTPUT",
    "SECTION_SUMMARY",
    "SIGNAL_CALCULATOR",
    "TIME_WINDOW",
]
